name: CH_ACWE
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7.12
  - numpy=1.20.3
  - scipy=1.5.3
  - sunpy=2.1.2
  - scikit-image=0.19.3
  - matplotlib=3.5.2
  - astropy=4.1
  - pandas=1.3.4
  - aiapy=0.6.4
  - imageio=2.19.1
  - reproject=0.8
  - notebook=6.4.11
  - ipywidgets=7.7.0
  - drms=0.6.2
  - glob2
  - pip
